sonar.projectName=SONAR_PROJECT_KEY
sonar.projectKey=SONAR_PROJECT_KEY
sonar.host.url=SONAR_HOST_URL
sonar.login=SONAR_LOGIN
sonar.sources=src
sonar.exclusions=
sonar.dynamicAnalysis=reuseReports
sonar.jacoco.reportPath=targetjacoco.exec
sonar.junit.reportPaths=targetsurefire-reports